openapi: 3.0.0

info:
  title: Learning Path Catalog API
  version: 1.0.0
  description: >
    API ini digunakan untuk tampilan Catalog Learning Path.
    Digunakan untuk menampilkan list learning path, search, filter,
    detail learning path, delete (admin), dan navbar user setelah login.

servers:
  - url: https://api.vareway.com/v1
    description: Production Server
  - url: http://localhost:3000/v1
    description: Development Server

paths:

  # GET ALL + SEARCH + FILTER
  
  /learning-path:
    get:
      summary: Get all learning path + search + filter kategori + filter level
      tags:
        - Learning Path
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search learning path berdasarkan judul (search bar navbar)

        - in: query
          name: category
          schema:
            type: string
          description: Filter kategori (Frontend, Backend, Cyber Security, dll)

        - in: query
          name: level
          schema:
            type: string
            enum: [beginner, intermediate, advanced]
          description: Filter tingkat learning path

        - in: query
          name: id
          schema:
            type: integer
          description: Parameter tambahan ID untuk filter tertentu

      responses:
        '200':
          description: Data learning path berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LearningPath'

  
  # GET DETAIL LEARNING PATH
  
  /learning-path/{id}:
    get:
      summary: Get detail learning path berdasarkan ID
      tags:
        - Learning Path
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID learning path yang diklik
      responses:
        '200':
          description: Detail learning path ditemukan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningPathDetail'
        '404':
          description: Learning path tidak ditemukan

    
    # DELETE LEARNING PATH (ADMIN)
    
    delete:
      summary: Delete learning path berdasarkan ID
      tags:
        - Learning Path
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Learning path berhasil dihapus

  
  # NAVBAR USER
  
  /user/profile:
    get:
      summary: Get data user untuk navbar (foto dan nama)
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Data user berhasil diambil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized


# COMPONENTS

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        photo:
          type: string
          example: https://cdn.example.com/user.png

    LearningPath:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        thumbnail:
          type: string
          example: https://cdn.example.com/thumbnail.png
        category:
          type: string
        level:
          type: string
        rating:
          type: number

    LearningPathDetail:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        thumbnail:
          type: string
        category:
          type: string
        level:
          type: string
        modules:
          type: array
          items:
            type: object
            properties:
              module_id:
                type: integer
              module_title:
                type: string
              duration:
                type: string
